### ISSUE TITLE
Connect failed. Error:  habitica.com returned (400) Bad Request

### ISSUE THREAD

**Issue by idealclover** [HabitRPG/habitica-zapier#2] opened 2018-01-25 17:30 UTC
I followed the steps and authorized to zapier, and then on the https://oldgods.net/habitica/task_adjustor.html I found my task's task number. But when testing it said "We had trouble sending your test through. Please try again. Error: habitica.com returned (400) Bad Request and said "Invalid request parameters."
Thanks a lot~

**Comment by Alys** [comment] 2020-02-23 03:57
I'm sorry no one ever helped with this. I'm closing it since the issue is old but if you or anyone else has trouble using the official Zapier integration, please post in Habitica's [Report a Bug](https://habitica.com/groups/guild/a29da26b-37de-4a71-b0c6-48e72a900dac) guild. If the problem turns out to be from a bug in the Zapier integration, we'll open a new issue here.

**Closed as completed by Alys** 2020-02-23 03:57 UTC
